const ICONS={menu:['M3 6h18M3 12h18M3 18h18'],close:['M6 6l12 12M6 18L18 6'],search:['M21 21l-5-5','circle:10.5,10.5,7.5'],save:['M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h12l4 4v12a2 2 0 0 1-2 2zM7 3v6h10V3M7 21v-8h10v8'],file:['M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M8 13h8M8 17h6'],settings:['M4 7h16M4 17h16','circle:9,7,2','circle:15,17,2'],edit:['M12 20h9M16 3l5 5L9 20l-5 1 1-5z'],user:['circle:12,7,4','M4 21v-2a6 6 0 0 1 6-6h4a6 6 0 0 1 6 6v2'],copy:['M9 9h12v12H9zM15 9V3H3v12h6'],plus:['M12 5v14M5 12h14']};
function svg(name){const ns='http://www.w3.org/2000/svg',el=document.createElementNS(ns,'svg');el.setAttribute('viewBox','0 0 24 24');el.setAttribute('fill','none');el.setAttribute('stroke','currentColor');el.setAttribute('stroke-width','1.8');el.setAttribute('stroke-linecap','round');el.setAttribute('stroke-linejoin','round');el.setAttribute('aria-hidden','true');for(const shape of ICONS[name]||[]){let child;if(shape.startsWith('circle:')){child=document.createElementNS(ns,'circle');const [x,y,r]=shape.slice(7).split(',');child.setAttribute('cx',x);child.setAttribute('cy',y);child.setAttribute('r',r);}else{child=document.createElementNS(ns,'path');child.setAttribute('d',shape);}el.appendChild(child);}return el;}
export function initGestionaleUI(){
  if(document.documentElement.dataset.gestionaleUI)return;document.documentElement.dataset.gestionaleUI='true';
  const sidebar=document.querySelector('.sidebar'),topbar=document.querySelector('.topbar'),main=document.querySelector('.main');
  if(sidebar&&topbar){
    sidebar.id='app-navigation';sidebar.setAttribute('aria-label','Navigazione del gestionale');
    if(!sidebar.querySelector('[href="porzioni.html"]')){const link=document.createElement('a');link.href='porzioni.html';link.className='sidebar-link';link.append(svg('file'),document.createTextNode('Porzioni'));sidebar.querySelector('.sidebar-section')?.appendChild(link);}
    const current=location.pathname.split('/').pop();sidebar.querySelectorAll('a').forEach(a=>{if(a.getAttribute('href')===current){a.classList.add('active');a.setAttribute('aria-current','page');}else{a.classList.remove('active');a.removeAttribute('aria-current');}});
    const toggle=document.createElement('button');toggle.type='button';toggle.id='nav-toggle';toggle.className='btn btn-ghost btn-icon nav-toggle';toggle.setAttribute('aria-controls',sidebar.id);toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Apri menu');toggle.appendChild(svg('menu'));topbar.prepend(toggle);
    const head=document.createElement('div');head.className='nav-heading';head.appendChild(document.createTextNode('Studio Cortese'));const close=document.createElement('button');close.type='button';close.className='btn btn-ghost btn-icon nav-close';close.setAttribute('aria-label','Chiudi menu');close.appendChild(svg('close'));head.appendChild(close);sidebar.prepend(head);
    const backdrop=document.createElement('button');backdrop.type='button';backdrop.className='nav-backdrop';backdrop.id='nav-backdrop';backdrop.setAttribute('aria-label','Chiudi menu');backdrop.tabIndex=-1;backdrop.hidden=true;document.body.appendChild(backdrop);
    const mobile=matchMedia('(max-width:1024px)');let previousFocus,previousOverflow='';
    const setOpen=(open,restore=true)=>{if(open&&!mobile.matches)return;const wasOpen=document.body.classList.contains('nav-open');if(open&&!wasOpen){previousFocus=document.activeElement;previousOverflow=document.body.style.overflow;}
      document.body.classList.toggle('nav-open',open);toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Chiudi menu':'Apri menu');backdrop.hidden=!open;if(main)main.inert=open;sidebar.inert=mobile.matches&&!open;sidebar.setAttribute('aria-hidden',String(mobile.matches&&!open));
      if(open){document.body.style.overflow='hidden';(sidebar.querySelector('[aria-current=page]')||close).focus();}else if(wasOpen){document.body.style.overflow=previousOverflow;if(restore)previousFocus?.focus();}};
    toggle.onclick=()=>setOpen(!document.body.classList.contains('nav-open'));close.onclick=backdrop.onclick=()=>setOpen(false);sidebar.addEventListener('click',e=>{if(e.target.closest('a'))setOpen(false,false);});
    mobile.addEventListener('change',()=>setOpen(false));setOpen(false,false);
    document.addEventListener('keydown',e=>{if(!document.body.classList.contains('nav-open'))return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();setOpen(false);return;}if(e.key==='Tab'){const nodes=[toggle,...sidebar.querySelectorAll('a,button')].filter(n=>!n.disabled);e.preventDefault();const current=nodes.indexOf(document.activeElement);nodes[(current+(e.shiftKey?-1:1)+nodes.length)%nodes.length].focus();}});
  }
  document.querySelectorAll('.search-field,.search-wrap').forEach(wrap=>{
    const input=wrap.querySelector('input');if(!input)return;wrap.classList.add('search-field');if(!input.getAttribute('aria-label'))input.setAttribute('aria-label',input.placeholder||'Cerca');input.setAttribute('autocomplete','off');
    if(!wrap.querySelector('svg'))wrap.prepend(svg('search'));
    const clear=document.createElement('button');clear.type='button';clear.className='search-clear';clear.textContent='×';clear.setAttribute('aria-label','Cancella ricerca');clear.hidden=!input.value;wrap.appendChild(clear);
    input.addEventListener('input',()=>clear.hidden=!input.value);clear.onclick=()=>{input.value='';clear.hidden=true;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();};
    wrap._updateSearchClear=()=>clear.hidden=!input.value;
  });
  document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-row-open]')){e.preventDefault();e.target.click();}});
  document.querySelectorAll('.breadcrumb-link').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button');el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});});
  const descriptors={'btn-pdf':['file','Esporta PDF'],'btn-word':['file','Esporta Word'],'btn-salva':['save','Salva piano'],'btn-vai-paziente':['user','Scheda paziente'],'btn-clone':['copy','Clona piano'],'btn-edit-meta':['edit','Modifica info'],'btn-edit-patient':['edit','Modifica anagrafica'],'btn-save-patient':['save','Salva paziente'],'btn-save-visit':['save','Salva visita'],'btn-save-alimento':['save','Salva alimento'],'btn-salva-testi':['save','Salva testi'],'btn-salva-consig':['save','Salva indicazioni'],'btn-save-pdf':['save','Salva preferenze'],'btn-nuovo-paziente':['plus','Nuovo paziente'],'btn-nuova-visita':['plus','Nuova visita'],'btn-nuovo-alimento':['plus','Nuovo alimento'],'btn-nuova-dieta':['plus','Nuova dieta'],'btn-nuova-globale':['plus','Nuova dieta']};
  for(const [id,[name,label]] of Object.entries(descriptors)){const button=document.getElementById(id);if(button)button.replaceChildren(svg(name),document.createTextNode(label));}
  document.querySelectorAll('.tab-btn,.et-btn').forEach(button=>{if(!button.querySelector('svg'))button.textContent=button.textContent.replace(/^[\s\p{Extended_Pictographic}\uFE0F\u200D]+/u,'').trim();});
  document.querySelectorAll('[data-ui-icon]').forEach(el=>el.prepend(svg(el.dataset.uiIcon)));
}
export function updateSearchControls(){document.querySelectorAll('.search-field').forEach(w=>w._updateSearchClear?.());}
