import {sb,getAllRows} from './supabase.js?v=20261009-3';
import {setHTML,escapeHtml,guard} from './safe-dom.js?v=20261009-3';
export const DIET_TYPES={onnivora:'Onnivora',carnivora:'Carnivora',vegetariana:'Vegetariana',vegana:'Vegana',pescetariana:'Pescetariana',altra:'Altra / non specificata'};
export function patientDietType(patient){const v=String(patient.vegetariano_vegano||patient.tipo_dieta_strutturato||'').trim().toLowerCase();return Object.hasOwn(DIET_TYPES,v)?v:'altra';}
function explain(error){if(['PGRST202','PGRST205','42P01','42703'].includes(error.code))return new Error('Modelli non ancora attivati: esegui db/003_modelli_dieta.sql su Supabase, dopo le migrazioni 001 e 002.');return error;}
async function result(promise){try{const {data}=await promise.throwOnError();return data;}catch(error){throw explain(error);}}
export async function loadModels(){try{return await getAllRows(()=>sb.from('modelli_dieta').select('*').order('nome').order('id'));}catch(error){throw explain(error);}}
export async function loadModelUsage(id){try{return await getAllRows(()=>sb.from('modelli_dieta_utilizzi').select('*,pazienti(nome,cognome),diete(nome,attiva)').eq('modello_id',id).order('used_at',{ascending:false}).order('id'));}catch(error){throw explain(error);}}
export const createModel=(dietId,v)=>result(sb.rpc('nutri_crea_modello',{p_dieta_id:dietId,p_nome:v.nome,p_tipo_dieta:v.tipo_dieta,p_patologie_ids:v.patologie_ids,p_descrizione:v.descrizione}));
export const updateModel=(id,v)=>result(sb.rpc('nutri_aggiorna_modello',{p_id:id,p_nome:v.nome,p_tipo_dieta:v.tipo_dieta,p_patologie_ids:v.patologie_ids,p_descrizione:v.descrizione,p_attivo:v.attivo}));
export const applyModel=(id,patientId,name,codes)=>result(sb.rpc('nutri_applica_modello',{p_modello_id:id,p_paziente_id:patientId,p_nome:name,p_avvisi_confermati:codes}));
export const cloneDiet=(id,patientId,codes)=>result(sb.rpc('nutri_clone_dieta_con_modello',{p_dieta_id:id,p_paziente_id:patientId,p_avvisi_confermati:codes}));
export function filterModels(models,{q='',type='',path='',archived=false}={}){return models.filter(m=>(archived?!m.attivo:m.attivo)&&(!type||m.tipo_dieta===type)&&(!path||m.patologie_ids?.includes(path))&&(!q||(m.nome+' '+(m.descrizione||'')).toLocaleLowerCase('it').includes(q.toLocaleLowerCase('it'))));}
export function modelPlan(model){const plan={};for(const p of model.pasti||[]){plan[p.settimana]??={};plan[p.settimana][p.giorno]??={};(plan[p.settimana][p.giorno][p.momento]??=[]).push({...p,kcal:p.kcal_calcolate,prot:p.proteine_calcolate,carb:p.carboidrati_calcolati,lip:p.lipidi_calcolati});}return plan;}
function dialog(html){const el=document.createElement('dialog');el.className='model-dialog';setHTML(el,html);document.body.appendChild(el);el.showModal();return el;}
function removeDialog(el){el.close();el.remove();}
// Gli avvisi sono ricalcolati dal database e nuovamente controllati nella transazione.
export async function reviewModelWarnings(modelId,patientId,modelName,patientName){
 const warnings=await result(sb.rpc('nutri_modello_avvisi',{p_modello_id:modelId,p_paziente_id:patientId}));
 if(!Array.isArray(warnings))throw new Error('Risposta degli avvisi non valida. Riprova.');
 if(!warnings.length)return [];
 return new Promise(resolve=>{
  const blocked=warnings.some(w=>w.bloccante),el=dialog(`<div class="modal-header"><h3>Verifica il modello</h3></div><div class="modal-body"><p><strong>${escapeHtml(modelName)}</strong> per <strong>${escapeHtml(patientName)}</strong></p><ul class="model-warnings">${warnings.map(w=>`<li>${escapeHtml(w.messaggio)}</li>`).join('')}</ul>${blocked?'<p>Risolvi gli alimenti non disponibili prima di applicare il modello.</p>':'<label class="model-confirm"><input type="checkbox" data-ack> Ho verificato gli avvisi e desidero proseguire. Potrò adattare la nuova dieta al paziente.</label>'}</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-cancel>Annulla</button>${blocked?'':'<button type="button" class="btn btn-primary" data-confirm disabled>Conferma applicazione</button>'}</div>`);
  const finish=value=>{removeDialog(el);resolve(value);};el.addEventListener('cancel',event=>{event.preventDefault();finish(null);});el.querySelector('[data-cancel]').onclick=()=>finish(null);
  if(!blocked){el.querySelector('[data-ack]').onchange=event=>el.querySelector('[data-confirm]').disabled=!event.target.checked;el.querySelector('[data-confirm]').onclick=()=>finish(warnings.map(w=>w.codice));}
 });
}
export function openModelForm({catalog=[],model=null,defaultType='altra',pathIds=[],name='',onSave}){
 const title=model?'Modifica modello':'Crea modello',paths=model?.patologie_ids||pathIds;
 const el=dialog(`<form><div class="modal-header"><h3>${title}</h3><button type="button" class="modal-close" aria-label="Chiudi" data-cancel>×</button></div><div class="modal-body"><div class="alert alert-error" role="alert" data-error></div><div class="form-group"><label>Nome del modello *</label><input name="nome" maxlength="150" required value="${escapeHtml(model?.nome||name)}"></div><div class="form-group"><label>Tipo di dieta</label><select name="tipo_dieta">${Object.entries(DIET_TYPES).map(([id,label])=>`<option value="${id}" ${(model?.tipo_dieta||defaultType)===id?'selected':''}>${label}</option>`).join('')}</select></div><div class="form-group"><label>Descrizione per la ricerca</label><textarea name="descrizione" rows="2" maxlength="2000">${escapeHtml(model?.descrizione||'')}</textarea></div><fieldset class="model-paths"><legend>Patologie / categorie del paziente</legend><p>Usa le stesse voci del catalogo pazienti. L’associazione aiuta la ricerca; gli avvisi controllano anche le controindicazioni degli alimenti.</p><input type="search" placeholder="Filtra patologie…" aria-label="Filtra patologie" data-path-search><div class="model-path-list">${catalog.map(p=>`<label data-path-label><input type="checkbox" name="patologie" value="${escapeHtml(p.id)}" ${paths.includes(p.id)?'checked':''}>${escapeHtml(p.nome)}</label>`).join('')||'<p>Nessuna patologia nel catalogo.</p>'}</div></fieldset>${model?`<label class="model-confirm"><input type="checkbox" name="attivo" ${model.attivo?'checked':''}> Modello attivo (deseleziona per archiviare)</label>`:'<p class="model-help">Vengono copiati pasti, alternative e testi del piano salvato. Controlla eventuali riferimenti al paziente nei testi prima di creare il modello. La copia resta indipendente dalle diete.</p>'}</div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-cancel>Annulla</button><button type="submit" class="btn btn-primary">${title}</button></div></form>`);
 let busy=false;
 const close=()=>{if(!busy)removeDialog(el);};el.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=close);el.addEventListener('cancel',event=>{event.preventDefault();close();});
 el.querySelector('[data-path-search]').oninput=event=>el.querySelectorAll('[data-path-label]').forEach(label=>label.hidden=!label.textContent.toLocaleLowerCase('it').includes(event.target.value.toLocaleLowerCase('it')));
 el.querySelector('form').onsubmit=guard(async event=>{
  event.preventDefault();if(busy)return;const form=event.target,error=el.querySelector('[data-error]'),button=form.querySelector('[type=submit]');busy=true;button.disabled=true;error.classList.remove('show');
  try{await onSave({nome:form.elements.nome.value.trim(),tipo_dieta:form.elements.tipo_dieta.value,descrizione:form.elements.descrizione.value.trim(),patologie_ids:[...form.querySelectorAll('[name=patologie]:checked')].map(i=>i.value),attivo:model?form.elements.attivo.checked:true});removeDialog(el);}catch(e){error.textContent=e.message;error.classList.add('show');}finally{busy=false;button.disabled=false;}
 });return el;
}
